// CNS preclinical drug-discovery supply chain — data
// Tiers run bottom (0, instruments) to top (5, pharma programs).
// k: "chokepoint" = a node the chain genuinely concentrates on (verified single/few-source).
//    "gap" = a capability that does not exist at usable scale (an absence, not a supplier).
// Every chokepoint and gap was adversarially verified; the overstated ones were downgraded.
// rev/emp/hq/li from research; private-company figures are estimates (est.).

const TIERS = [
  { t:0, name:"Instruments & Equipment", c:"#5b8def" },
  { t:1, name:"Reagents, Cells & Consumables", c:"#36c6a8" },
  { t:2, name:"Human Models & Assays", c:"#a273ff" },
  { t:3, name:"CROs & Services", c:"#f0a93b" },
  { t:4, name:"Data & AI", c:"#ff6fa5" },
  { t:5, name:"Biotech & Pharma Programs", c:"#dfe5f3" },
];

// fields: id, n(name), t(tier), c(category), d(what they make/are),
//         rev, emp, hq, li(linkedin), pp(public|private), k(kind), w(why for chokepoint/gap)
const NODES = [
  // ----- TIER 0: INSTRUMENTS & EQUIPMENT -----
  {id:"tecan",n:"Tecan",t:0,c:"Liquid handling",d:"Pipetting robots (Fluent, EVO) that run cell culture, assay setup, and library prep.",rev:"~$1.06B (FY24)",emp:"~3,300",hq:"Männedorf, CH",li:"https://www.linkedin.com/company/tecan/",pp:"public"},
  {id:"hamilton",n:"Hamilton",t:0,c:"Liquid handling",d:"Microlab STAR pipetting workstations for genomics prep, screening, and biobanking.",rev:"~$1B+ (est., private)",emp:"~3,000+",hq:"Reno, NV",li:"https://www.linkedin.com/company/hamilton-company/",pp:"private"},
  {id:"beckman",n:"Beckman Coulter",t:0,c:"Liquid handling",d:"Biomek liquid handlers, centrifuges, and flow cytometers (Danaher).",rev:"Danaher LS ~$7B seg.",emp:"~11,000",hq:"Brea, CA",li:"https://www.linkedin.com/company/beckman-coulter/",pp:"public"},
  {id:"opentrons",n:"Opentrons",t:0,c:"Liquid handling",d:"Cheap open-source pipetting robots (OT-2, Flex) for small labs.",rev:"<$50M (est.)",emp:"~150",hq:"Brooklyn, NY",li:"https://www.linkedin.com/company/opentrons/",pp:"private"},
  {id:"sptlabtech",n:"SPT Labtech",t:0,c:"Liquid handling",d:"Nanoliter dispensers (mosquito, dragonfly) for miniaturized screening and NGS prep.",rev:"~$100-150M (est.)",emp:"~500",hq:"Melbourn, UK",li:"https://www.linkedin.com/company/spt-labtech/",pp:"private"},
  {id:"zeiss",n:"ZEISS Microscopy",t:0,c:"Imaging",d:"Confocal and light-sheet microscopes for imaging live organoids in 3D.",rev:"ZEISS grp ~€10B",emp:"~43,000 (grp)",hq:"Oberkochen, DE",li:"https://www.linkedin.com/company/zeiss/",pp:"private"},
  {id:"leica",n:"Leica Microsystems",t:0,c:"Imaging",d:"Confocal and widefield microscopes for organoid and neuro imaging (Danaher).",rev:"Danaher LS seg.",emp:"~4,000+",hq:"Wetzlar, DE",li:"https://www.linkedin.com/company/leica-microsystems/",pp:"public"},
  {id:"nikon",n:"Nikon Instruments",t:0,c:"Imaging",d:"Inverted and confocal microscopes (Ti2, AX) standard in iPSC and organoid labs.",rev:"Healthcare ~$650-700M",emp:"~19,000 (corp)",hq:"Tokyo, JP",li:"https://www.linkedin.com/company/nikon-instruments-inc-/",pp:"public"},
  {id:"moldev",n:"Molecular Devices",t:0,c:"Imaging",d:"ImageXpress high-content imagers and plate readers for organoid phenotypic screens.",rev:"~$400-500M (est.)",emp:"~1,000+",hq:"San Jose, CA",li:"https://www.linkedin.com/company/molecular-devices/",pp:"private"},
  {id:"revvity",n:"Revvity",t:0,c:"Imaging",d:"Opera Phenix / Operetta high-content confocal imagers for 3D organoid screening.",rev:"~$2.8B (FY24)",emp:"~11,000",hq:"Waltham, MA",li:"https://www.linkedin.com/company/revvity/",pp:"public"},
  {id:"cephla",n:"Cephla (Squid)",t:0,c:"Imaging",d:"Low-cost open automated microscopy for daily organoid QC imaging.",rev:"private, small",emp:"est. small",hq:"USA",li:"",pp:"private"},
  {id:"tenx",n:"10x Genomics",t:0,c:"Single-cell + spatial",d:"Chromium single-cell instruments and the Xenium spatial imager, the default single-cell and a leading spatial readout.",rev:"~$611M (FY24)",emp:"~1,300",hq:"Pleasanton, CA",li:"https://www.linkedin.com/company/10xgenomics/",pp:"public",k:"chokepoint",w:"Chromium is the de facto droplet single-cell standard and Xenium/Visium anchor much of spatial. Single-cell is no longer single-source (Parse and Scale ship instrument-free kits, and Tahoe-100M itself ran on Parse), but spatial is tightly held and 10x defends both with aggressive patent litigation. A concentration risk to manage, hardest in spatial."},
  {id:"parse",n:"Parse Biosciences",t:0,c:"Single-cell",d:"Instrument-free split-pool scRNA-seq kits (Evercode) that scale to millions of cells; now owned by QIAGEN.",rev:"~$40M (2026 est.)",emp:"~250",hq:"Seattle, WA",li:"https://www.linkedin.com/company/parse-biosciences/",pp:"private"},
  {id:"scalebio",n:"Scale Biosciences",t:0,c:"Single-cell",d:"Split-pool single-cell kits (RNA, multiomics) for very high-throughput runs; acquired by 10x in 2025.",rev:"<$50M (est.)",emp:"~150",hq:"San Diego, CA",li:"https://www.linkedin.com/company/scale-biosciences/",pp:"private"},
  {id:"bruker_sp",n:"Bruker Spatial (NanoString)",t:0,c:"Spatial",d:"CosMx single-molecule imaging and GeoMx profiling for high-plex spatial.",rev:"Bruker grp ~$3.4B",emp:"~11,000 (grp)",hq:"Seattle, WA",li:"https://www.linkedin.com/company/bruker/",pp:"public"},
  {id:"vizgen",n:"Vizgen",t:0,c:"Spatial",d:"MERSCOPE MERFISH platform for single-molecule spatial transcriptomics.",rev:"<$50M (est.)",emp:"~200",hq:"Cambridge, MA",li:"https://www.linkedin.com/company/vizgen/",pp:"private"},
  {id:"akoya",n:"Akoya Biosciences",t:0,c:"Spatial",d:"PhenoCycler/CODEX high-plex spatial proteomics imaging.",rev:"~$80-90M (FY24)",emp:"~300",hq:"Marlborough, MA",li:"https://www.linkedin.com/company/akoya-biosciences/",pp:"public"},
  {id:"maxwell",n:"MaxWell Biosystems",t:0,c:"Electrophysiology (MEA)",d:"High-density CMOS MEA (MaxOne/MaxTwo, ~26k electrodes/well) for organoid network activity at single-cell resolution; the density leader.",rev:"<$20M (est.)",emp:"~70",hq:"Zurich, CH",li:"https://www.linkedin.com/company/maxwell-biosystems/",pp:"private"},
  {id:"axion",n:"Axion BioSystems",t:0,c:"Electrophysiology (MEA)",d:"Maestro multiwell MEA, the workhorse for higher-throughput neural and cardiac activity assays (9 of top-10 pharma).",rev:"~$25-50M (est.)",emp:"~150",hq:"Atlanta, GA",li:"https://www.linkedin.com/company/axion-biosystems/",pp:"private"},
  {id:"3brain",n:"3Brain",t:0,c:"Electrophysiology (MEA)",d:"CMOS HD-MEA (BioCAM) with a 3D needle option built for recording inside brain organoids.",rev:"<$15M (est.)",emp:"~30-50",hq:"Pfungen, CH",li:"https://www.linkedin.com/company/3brain-ag",pp:"private"},
  {id:"mcs",n:"Multi Channel Systems",t:0,c:"Electrophysiology (MEA)",d:"Benchtop MEA systems and amplifiers for neural cultures, slices, and organoids (Harvard Bioscience).",rev:"HBIO ~$100M",emp:"~50-80",hq:"Reutlingen, DE",li:"https://www.linkedin.com/company/multi-channel-systems/",pp:"public"},
  {id:"nanion",n:"Nanion",t:0,c:"Electrophysiology",d:"Automated patch-clamp systems for ion-channel electrophysiology.",rev:"private",emp:"est.",hq:"Munich, DE",li:"",pp:"private"},
  {id:"illumina",n:"Illumina",t:0,c:"Sequencing",d:"NovaSeq short-read sequencers that read out most scRNA-seq and sequencing-based spatial libraries.",rev:"~$4.37B (FY24)",emp:"~9,500",hq:"San Diego, CA",li:"https://www.linkedin.com/company/illumina/",pp:"public",k:"chokepoint",w:"About two-thirds of installed sequencers and most single-cell readouts run on Illumina, the deepest single dependency in the stack. But the moat is contested and declining: Element AVITI, Ultima (which read out Tahoe-100M), and MGI are in production, and imaging-based spatial like Xenium needs no sequencer at all."},
  {id:"pacbio",n:"PacBio",t:0,c:"Sequencing",d:"Long-read HiFi sequencers (Revio) for full-length isoform and structural-variant work.",rev:"~$154M (FY24)",emp:"~700",hq:"Menlo Park, CA",li:"https://www.linkedin.com/company/pacific-biosciences/",pp:"public"},
  {id:"nanopore",n:"Oxford Nanopore",t:0,c:"Sequencing",d:"Nanopore long-read sequencers that read native DNA/RNA in real time.",rev:"~£170M (FY24)",emp:"~1,000+",hq:"Oxford, UK",li:"https://www.linkedin.com/company/oxford-nanopore-technologies/",pp:"public"},
  {id:"element",n:"Element Biosciences",t:0,c:"Sequencing",d:"AVITI short-read sequencers positioned as the lower-cost Illumina alternative.",rev:"<$100M (est.)",emp:"~400",hq:"San Diego, CA",li:"https://www.linkedin.com/company/element-biosciences/",pp:"private"},
  {id:"sartorius_hw",n:"Sartorius",t:0,c:"Culture / live imaging",d:"Bioreactors, Incucyte live-cell imaging, and cell counters for scaled iPSC/organoid culture.",rev:"~€3.4B (FY24)",emp:"~14,000",hq:"Göttingen, DE",li:"https://www.linkedin.com/company/sartorius/",pp:"public"},
  {id:"cytena",n:"Cytena (BICO)",t:0,c:"Culture automation",d:"Single-cell printers for clonality plus benchtop organoid-handling automation.",rev:"BICO grp ~$190M",emp:"~150",hq:"Freiburg, DE",li:"https://www.linkedin.com/company/cytena/",pp:"public"},
  {id:"phc",n:"PHCbi",t:0,c:"Incubators",d:"CO2 and tri-gas incubators widely used for stem-cell and organoid culture.",rev:"PHC grp ~¥350B",emp:"~9,000",hq:"Tokyo, JP",li:"https://www.linkedin.com/company/phchd/",pp:"public"},
  {id:"emulate_hw",n:"Emulate (Zoë)",t:0,c:"Organ-chip hardware",d:"Organ-on-chip instruments and microfluidic chips that flow media through tissue models.",rev:"~$30-50M (est.)",emp:"~120-180",hq:"Boston, MA",li:"https://www.linkedin.com/company/emulatebio/",pp:"private"},
  {id:"agilent",n:"Agilent (Seahorse)",t:0,c:"Plate readers / metabolism",d:"BioTek plate readers/imagers and Seahorse metabolic-flux analyzers.",rev:"~$6.5B (FY24)",emp:"~17,000",hq:"Santa Clara, CA",li:"https://www.linkedin.com/company/agilent-technologies/",pp:"public",k:"chokepoint",w:"Seahorse XF is the de facto standard and the only platform measuring oxygen consumption and acidification (glycolysis) together in a plate. It is not the only way to read metabolism (Oroboros and Lucid's Resipher compete on oxygen consumption), but for the simultaneous high-throughput readout there is effectively one supplier."},
  {id:"bd",n:"BD Biosciences",t:0,c:"Flow cytometry",d:"FACS cytometers and cell sorters used to phenotype, sort, and QC iPSC and neural cells.",rev:"BD grp ~$20B",emp:"~70,000 (BD)",hq:"Franklin Lakes, NJ",li:"https://www.linkedin.com/company/bd1/",pp:"public"},
  {id:"cytek",n:"Cytek Biosciences",t:0,c:"Flow cytometry",d:"Aurora spectral cytometers for high-parameter immunophenotyping.",rev:"~$200M (FY24)",emp:"~700",hq:"Fremont, CA",li:"https://www.linkedin.com/company/cytek-biosciences/",pp:"public"},
  {id:"lonza",n:"Lonza Nucleofector",t:0,c:"Transfection / editing delivery",d:"Nucleofector electroporation, the most-cited way to get CRISPR RNPs and mRNA into hard-to-transfect iPSCs; MaxCyte and Thermo's Neon compete.",rev:"Lonza grp ~CHF 6.6B",emp:"~18,000 (grp)",hq:"Basel, CH",li:"https://www.linkedin.com/company/lonza/",pp:"public"},

  // ----- TIER 1: REAGENTS, CELLS & CONSUMABLES -----
  {id:"corning",n:"Matrigel (EHS-tumor ECM)",t:1,c:"ECM / matrices",d:"The mouse-tumor basement membrane nearly every brain organoid is grown in; Corning leads, and Geltrex and Cultrex are the same extract from other vendors.",rev:"Corning LS ~$1.1B",emp:"Corning ~57,000",hq:"Corning, NY",li:"https://www.linkedin.com/company/corning-life-sciences/",pp:"public",k:"chokepoint",w:"The chokepoint is the material, not the vendor. Matrigel, Thermo's Geltrex, and Bio-Techne's Cultrex are all the same animal-derived, chemically undefined, lot-variable extract drawn from one EHS mouse-tumor source, and no defined synthetic matrix has displaced it at scale. The 2022 shortage hit all of them at once, which is the tell."},
  {id:"gibco",n:"Thermo Fisher (Gibco)",t:1,c:"Media & growth factors",d:"Gibco media, B-27/N-2 neural supplements, and Geltrex, the default reagent ecosystem most iPSC SOPs are built on.",rev:"TMO ~$43B",emp:"~125,000",hq:"Waltham, MA",li:"https://www.linkedin.com/company/thermo-fisher-scientific/",pp:"public"},
  {id:"stemcell",n:"STEMCELL Technologies",t:1,c:"Media & kits",d:"mTeSR iPSC media and STEMdiff cerebral/midbrain organoid kits that productize published protocols.",rev:"~$1B (est., private)",emp:"~2,000+",hq:"Vancouver, CA",li:"https://www.linkedin.com/company/stemcell-technologies/",pp:"private"},
  {id:"jax",n:"KOLF2.1J / Jackson Lab",t:1,c:"iPSC reference lines",d:"Custodian and distributor of KOLF2.1J, the reference iPSC line anchoring the big neuro programs.",rev:"JAX ~$500M (mostly mice)",emp:"~3,000",hq:"Bar Harbor, ME",li:"https://www.linkedin.com/company/the-jackson-laboratory/",pp:"nonprofit",k:"chokepoint",w:"KOLF2.1J is the dominant reference iPSC line for CNS work and the shared backbone of iNDI, MorPhiC, and SSPsyGene across 100+ labs, so cross-lab comparability in neuro is pinned to essentially one genome distributed by Jackson Lab. A Sanger sibling clone (KOLF2.1S) and WTC-11 exist, but the consortia standardized on the JAX clone."},
  {id:"coriell",n:"Coriell Institute",t:1,c:"Patient cell biobank",d:"Runs the NIGMS and NIA legacy cell repositories, a deep decades-old source of consented patient-derived AD and PD fibroblast and lymphoblast lines.",rev:"~$30-50M (est., nonprofit)",emp:"~250-350",hq:"Camden, NJ",li:"https://www.linkedin.com/company/coriellinstitute/",pp:"nonprofit"},
  {id:"wicell",n:"WiCell",t:1,c:"iPSC reference lines",d:"Banks foundational hESC/iPSC reference lines (H9, the KOLF2 parental lineage) and runs cell-line QC.",rev:"~$10-20M (est.)",emp:"~50-100",hq:"Madison, WI",li:"https://www.linkedin.com/company/wicell-research-institute/",pp:"nonprofit"},
  {id:"cdi_r",n:"FUJIFILM CDI (cells)",t:1,c:"iPSC-derived cells",d:"iCell ready-to-use iPSC-derived neurons, astrocytes, and microglia at industrial scale.",rev:"~$50-100M (est.)",emp:"~300-500",hq:"Madison, WI",li:"https://www.linkedin.com/company/fujifilm-cellular-dynamics/",pp:"private"},
  {id:"peprotech",n:"PeproTech (Thermo)",t:1,c:"Growth factors",d:"Low-cost recombinant growth factors (FGF2, BDNF, GDNF, SHH, Noggin) for neural patterning.",rev:"~$180M (at acq.)",emp:"~500",hq:"Cranbury, NJ",li:"https://www.linkedin.com/company/peprotech/",pp:"public"},
  {id:"biotechne",n:"Bio-Techne (R&D Systems)",t:1,c:"Growth factors / small mol.",d:"Gold-standard recombinant growth factors plus Tocris small molecules (CHIR, SB431542) for neural induction; also Cultrex BME.",rev:"~$1.2B",emp:"~3,000",hq:"Minneapolis, MN",li:"https://www.linkedin.com/company/bio-techne/",pp:"public"},
  {id:"merck_ls",n:"Merck / MilliporeSigma",t:1,c:"Reagents (broad)",d:"The Sigma-Aldrich catalog, the broadest single inventory of culture reagents and chemicals.",rev:"LS div ~€9B",emp:"~63,000",hq:"Darmstadt, DE",li:"https://www.linkedin.com/company/emd-millipore/",pp:"public"},
  {id:"amsbio",n:"Amsbio (Cultrex)",t:1,c:"ECM / matrices",d:"Cultrex/rLaminin basement-membrane extract, the main animal-derived alternative sold against Matrigel.",rev:"~$30-60M (est.)",emp:"~100-150",hq:"Abingdon, UK",li:"https://www.linkedin.com/company/amsbio/",pp:"private"},
  {id:"cellendes",n:"Cellendes / Gelomics / QGel",t:1,c:"Defined hydrogels",d:"Fully synthetic, defined PEG hydrogels built to replace Matrigel, promising but not yet field-standard.",rev:"<$10M each (est.)",emp:"~10-50",hq:"DE / AU / CH",li:"https://www.linkedin.com/company/gelomics/",pp:"private"},
  {id:"idt",n:"IDT (Danaher)",t:1,c:"CRISPR reagents",d:"Synthetic guide RNAs, Cas9 RNPs, and custom oligos, the default for iPSC gene editing.",rev:"~$650M+",emp:"~2,000+",hq:"Coralville, IA",li:"https://www.linkedin.com/company/integrated-dna-technologies/",pp:"public"},
  {id:"synthego",n:"Synthego",t:1,c:"CRISPR reagents",d:"Synthetic sgRNAs and engineered knockout/knockin iPSC line services.",rev:"~$50-100M (est.)",emp:"~300-400",hq:"Redwood City, CA",li:"https://www.linkedin.com/company/synthego/",pp:"private"},
  {id:"twist",n:"Twist Bioscience",t:1,c:"Synthetic DNA",d:"Chip-synthesized oligo pools, gene fragments, and CRISPR guide libraries.",rev:"~$300M+",emp:"~2,000",hq:"S. San Francisco, CA",li:"https://www.linkedin.com/company/twist-bioscience/",pp:"public"},
  {id:"addgene",n:"Addgene",t:1,c:"Plasmid repository",d:"The nonprofit repository distributing the canonical published CRISPR constructs the field cites.",rev:"~$10-20M (est.)",emp:"~100",hq:"Watertown, MA",li:"https://www.linkedin.com/company/addgene/",pp:"nonprofit",k:"chokepoint",w:"Addgene is the de facto citation standard for published CRISPR plasmids: journals point to it and papers deposit there to get the accession numbers their methods cite. GenScript's MolecularCloud and DNASU exist, but neither displaces it for the cited academic tooling, so an edited-line program routes through one repository."},
  {id:"miltenyi",n:"Miltenyi Biotec",t:1,c:"Dissociation / separation",d:"MACS magnetic separation and the dissociation kits used to make single-cell suspensions from organoids.",rev:"~€1B (est.)",emp:"~4,500",hq:"Bergisch Gladbach, DE",li:"https://www.linkedin.com/company/miltenyi-biotec/",pp:"private"},
  {id:"biolegend",n:"BioLegend (Revvity)",t:1,c:"Antibodies",d:"Flow antibodies and TotalSeq oligo-tagged antibodies for CITE-seq multimodal single-cell.",rev:"~$380M (at acq.)",emp:"~1,000+",hq:"San Diego, CA",li:"https://www.linkedin.com/company/biolegend/",pp:"public"},
  {id:"cst",n:"Cell Signaling Tech",t:1,c:"Antibodies",d:"High-validation antibodies, especially phospho clones for neuronal signaling and tau.",rev:"~$300-400M (est.)",emp:"~1,000+",hq:"Danvers, MA",li:"https://www.linkedin.com/company/cell-signaling-technology/",pp:"private"},

  // ----- TIER 2: HUMAN MODELS & ASSAYS -----
  {id:"bitbio",n:"bit.bio",t:2,c:"iPSC neurons & glia",d:"opti-ox deterministic reprogramming makes defined, consistent iPSC neurons and glia off the shelf.",rev:"~$30M (est.)",emp:"~250-300",hq:"Cambridge, UK",li:"https://www.linkedin.com/company/bitbio",pp:"private"},
  {id:"cdi_m",n:"FUJIFILM CDI (iCell)",t:2,c:"iPSC neurons & glia",d:"Industrial-scale iCell neurons, astrocytes, and microglia; the original industrial iPSC manufacturer, though BrainXell and bit.bio now contest the neuron niche.",rev:"~$50-100M (est.)",emp:"~300-500",hq:"Madison, WI",li:"https://www.linkedin.com/company/fujifilm-cellular-dynamics/",pp:"private"},
  {id:"brainxell",n:"BrainXell",t:2,c:"iPSC neurons & glia",d:"Enriched iPSC neuron subtypes (cortical, motor, dopaminergic) and custom differentiation; claims 13 of the 15 top pharma.",rev:"~$4-9M",emp:"~45-50",hq:"Madison, WI",li:"https://www.linkedin.com/company/brainxell-inc",pp:"private"},
  {id:"neucyte",n:"NeuCyte",t:2,c:"iPSC neurons + assays",d:"SynFire dual-factor excitatory/inhibitory neurons plus MEA-based functional screening on them.",rev:"~$1-3M (est.)",emp:"~15-25",hq:"Sunnyvale, CA",li:"https://www.linkedin.com/company/neucyte",pp:"private"},
  {id:"axol",n:"Axol Bioscience",t:2,c:"iPSC neurons & glia",d:"axoCells iPSC neuron panel (cortical, striatal, sensory, motor) plus microglia and astrocytes.",rev:"~$10M",emp:"~60",hq:"Cambridge, UK",li:"https://www.linkedin.com/company/axol-bioscience-ltd-",pp:"private"},
  {id:"ncardia",n:"Ncardia",t:2,c:"iPSC cells + services",d:"iPSC-derived cortical/peripheral neurons and cardiomyocytes plus differentiation and assay services.",rev:"~$10-20M (est.)",emp:"~80-120",hq:"Leiden, NL",li:"https://www.linkedin.com/company/ncardia",pp:"private"},
  {id:"anatomic",n:"Anatomic",t:2,c:"iPSC sensory neurons",d:"RealDRG cryopreserved iPSC sensory neurons at high purity, mainly for pain research.",rev:"~$1-3M (est.)",emp:"~10-25",hq:"Minneapolis, MN",li:"https://www.linkedin.com/company/anatomicincorporated",pp:"private"},
  {id:"ahead_m",n:"a:head bio",t:2,c:"Brain organoid platform",d:"AI-driven automated human brain-organoid platform for CNS drug discovery, lead indication Dravet.",rev:"pre-revenue",emp:"~18",hq:"Vienna, AT",li:"https://www.linkedin.com/company/aheadbio",pp:"private"},
  {id:"bot",n:"Brain Organoid Therapeutics",t:2,c:"Brain organoid platform",d:"Human brain-organoid drug screening and functional phenotyping as a service (SAHMRI spinout).",rev:"<$1M (est.)",emp:"~5-15",hq:"Adelaide, AU",li:"https://www.linkedin.com/company/brain-organoid-therapeutics",pp:"private"},
  {id:"organoth",n:"OrganoTherapeutics",t:2,c:"Assembloids",d:"Human midbrain organoids and assembloids that reproduce Parkinson's pathology.",rev:"<$1M (est.)",emp:"~5-15",hq:"Esch-sur-Alzette, LU",li:"https://www.linkedin.com/company/organotherapeutics",pp:"private"},
  {id:"emulate_m",n:"Emulate (Brain-Chip)",t:2,c:"Organ-on-chip",d:"Brain-Chip and BBB organ-chips plus lab services modeling neuro and blood-brain-barrier biology.",rev:"~$30-50M (est.)",emp:"~120-180",hq:"Boston, MA",li:"https://www.linkedin.com/company/emulatebio",pp:"private"},
  {id:"mimetas",n:"MIMETAS",t:2,c:"Organ-on-chip",d:"OrganoPlate 384-well perfused organ-on-chip plus neuro/BBB models as a service.",rev:"~€30-60M (est.)",emp:"~110-150",hq:"Oegstgeest, NL",li:"https://www.linkedin.com/company/mimetas",pp:"private"},
  {id:"cnbio",n:"CN Bio",t:2,c:"Organ-on-chip",d:"PhysioMimix microphysiological systems, strongest in liver, expanding to other tissues.",rev:"~£2-5M",emp:"~40-70",hq:"Cambridge, UK",li:"https://uk.linkedin.com/company/cnbio",pp:"private"},
  {id:"hesperos",n:"Hesperos",t:2,c:"Organ-on-chip",d:"Functional, label-free human-on-a-chip multi-organ service with neuron/NMJ and BBB modules.",rev:"~$5M",emp:"~45-58",hq:"Orlando, FL",li:"https://www.linkedin.com/company/hesperos-inc.",pp:"private"},
  {id:"axosim",n:"AxoSim",t:2,c:"Organ-on-chip / CRO",d:"NerveSim nerve-on-chip and BrainSim 3D organoid assays (owns ex-StemoniX microBrain).",rev:"~$2-5M",emp:"~10-35",hq:"New Orleans, LA",li:"https://www.linkedin.com/company/axosim",pp:"private"},
  {id:"netseq",n:"Cerevance NETSseq",t:2,c:"Human brain tissue",d:"Cell-type-specific profiling of human post-mortem brain tissue for target discovery.",rev:"pre-revenue platform",emp:"see Cerevance",hq:"Cambridge, MA",li:"https://www.linkedin.com/company/cerevance",pp:"private"},
  {id:"bioivt",n:"BioIVT",t:2,c:"Human biospecimens",d:"One of a handful of large commercial suppliers of consented human biospecimens, including CNS tissue and CSF.",rev:"~$200M+ (est.)",emp:"~1,000+",hq:"Westbury, NY",li:"https://www.linkedin.com/company/bioivt",pp:"private"},
  {id:"neurobiobank",n:"NIH NeuroBioBank",t:2,c:"Human brain tissue",d:"The federal network of six brain banks (9,000+ specimens) that is the real backbone of post-mortem human brain tissue supply.",rev:"NIH-funded",emp:"n/a",hq:"USA (6 sites)",li:"",pp:"public"},
  {id:"yamanaka",n:"Yamanaka iPSC IP",t:2,c:"Reprogramming licensing",d:"The Kyoto / iPS Academia Japan patent estate on the four reprogramming factors; a broadly-licensed FTO gate (250+ licensees) for commercial iPSC production, with the core US patents expiring around 2027.",rev:"licensing",emp:"n/a",hq:"Kyoto, JP",li:"",pp:"licensing"},

  // ----- TIER 3: CROs & SERVICES -----
  {id:"charles",n:"Charles River",t:3,c:"Discovery / safety CRO",d:"Full-stack discovery-through-safety CRO with CNS pharmacology, behavioral models, and IND-enabling tox; the largest single node on the IND path (~33%).",rev:"~$4.1B (FY24)",emp:"~20,000",hq:"Wilmington, MA",li:"https://www.linkedin.com/company/charles-river-laboratories",pp:"public"},
  {id:"evotec",n:"Evotec",t:3,c:"Discovery CRO",d:"Integrated discovery / co-discovery CRO with deep neuroscience and iPSC disease-modeling platforms.",rev:"~€790M (FY24)",emp:"~4,200",hq:"Hamburg, DE",li:"https://www.linkedin.com/company/evotec",pp:"public"},
  {id:"wuxi",n:"WuXi AppTec",t:3,c:"Discovery CRO",d:"End-to-end discovery chemistry and biology at scale; touched ~21% of FDA small-molecule approvals, though only ~12-15% of the discovery-CRO market.",rev:"~$5.4B (FY24)",emp:"~38,000",hq:"Shanghai, CN",li:"https://www.linkedin.com/company/wuxi-apptec",pp:"public"},
  {id:"pharmaron",n:"Pharmaron",t:3,c:"Discovery CRO",d:"Integrated discovery and bioscience CRO running in-vitro and in-vivo CNS pharmacology and DMPK.",rev:"~$1.7B (FY24)",emp:"~25,000",hq:"Beijing, CN",li:"https://www.linkedin.com/company/pharmaron",pp:"public"},
  {id:"crownbio",n:"Crown Bioscience",t:3,c:"Organoid CRO",d:"Translational CRO with a large patient-derived tumor-organoid biobank and screening (oncology-led).",rev:"~$60-200M",emp:"~570+",hq:"San Diego, CA",li:"https://www.linkedin.com/company/crown-bioscience",pp:"private"},
  {id:"cellesce",n:"Cellesce (Danaher)",t:3,c:"Organoid bioprocess",d:"Scalable, reproducible expansion of patient-derived organoids for screening (now Molecular Devices).",rev:"folded into Danaher",emp:"~10-20",hq:"Cardiff, UK",li:"https://www.linkedin.com/company/cellesce-ltd",pp:"public"},
  {id:"neuroproof",n:"NeuroProof",t:3,c:"MEA / CNS screening CRO",d:"Records MEA network activity and applies pattern fingerprinting for efficacy, neurotox, and mechanism.",rev:"~$1-3M (est.)",emp:"~10",hq:"Rostock, DE",li:"https://www.linkedin.com/company/neuroproof-gmbh",pp:"private"},
  {id:"metrion",n:"Metrion Biosciences",t:3,c:"Ion-channel CRO",d:"Patch-clamp, MEA, and imaging assays for pain, epilepsy, and neurodegeneration.",rev:"~£3-6M (est.)",emp:"~30-50",hq:"Cambridge, UK",li:"https://uk.linkedin.com/company/metrion-biosciences",pp:"private"},
  {id:"azenta",n:"Azenta (GENEWIZ)",t:3,c:"scRNA-seq / NGS service",d:"GENEWIZ runs single-cell RNA-seq, bulk NGS, and sample prep as a service.",rev:"~$650M (FY24)",emp:"~3,000+",hq:"Burlington, MA",li:"https://www.linkedin.com/company/azenta-life-sciences",pp:"public"},
  {id:"c28bio",n:"28bio",t:3,c:"Organoid-MEA CRO",d:"Peripheral-nerve-on-chip on a multiwell MEA for scalable, longitudinal neurotoxicity readouts.",rev:"pre-revenue",emp:"~5-15 (est.)",hq:"USA",li:"https://www.linkedin.com/company/28bio",pp:"private"},
  {id:"definigen",n:"DefiniGEN",t:3,c:"iPSC services",d:"Custom iPSC line generation, CRISPR editing, and disease models as a service.",rev:"~$1-3M (est.)",emp:"~10-20",hq:"Cambridge, UK",li:"https://www.linkedin.com/company/definigen",pp:"private"},
  {id:"nhp",n:"NHP / cynomolgus supply",t:3,c:"Research models (IND-tox)",d:"Non-human primates for IND-enabling toxicology of biologics and gene therapies.",rev:"~$20k+/animal",emp:"few breeders",hq:"Mauritius / Cambodia / Vietnam",li:"",pp:"private",k:"chokepoint",w:"The real squeeze on the preclinical-to-IND path: cynomolgus macaques are about 79% of lab-NHP use, the field routes through a handful of breeder countries, and breeding runs on a roughly 4-year lead time. The live gate today is Cambodia, which supplies around 60% of US imports and sits under a CITES and laundering cloud (though exports remain legal), not the original 2020 China ban. Prices peaked above $20,000 in 2022-23, fell to about $11-13k, and are climbing again; US purpose-bred buildout and the FDA's 2025 push to cut NHP tox for antibodies are partial relief."},

  // ----- TIER 4: DATA & AI -----
  {id:"allen",n:"Allen Brain Atlas",t:4,c:"Reference atlas",d:"Public reference atlas of human and mouse brain cell types, expression, and connectivity. No drug arms.",rev:"~$500M+ seed (Allen)",emp:"n/a",hq:"Seattle, WA",li:"",pp:"public"},
  {id:"hca",n:"Human Cell Atlas",t:4,c:"Reference atlas",d:"Open consortium mapping every healthy human cell type, brain included. Reference, not perturbation.",rev:"CZI/Wellcome/NIH",emp:"n/a (consortium)",hq:"consortium",li:"",pp:"public"},
  {id:"hnoca",n:"HNOCA (organoid atlas)",t:4,c:"Organoid atlas",d:"Integrated single-cell atlas of human neural organoids (~1.77M cells, 36 datasets), the closest analog to a CNS dataset, and it has no perturbation layer.",rev:"academic",emp:"n/a",hq:"Munich / Zurich",li:"",pp:"public"},
  {id:"rosmap",n:"ROSMAP / AMP-AD",t:4,c:"Human brain cohort",d:"Post-mortem human brain multi-omics from aging cohorts (~2.3M nuclei). Observational disease-vs-control, no drug arms.",rev:"~$200M+ (AMP-AD)",emp:"n/a",hq:"Chicago, IL",li:"",pp:"public"},
  {id:"gtex",n:"GTEx",t:4,c:"Tissue reference",d:"Expression and eQTLs across ~50 human tissues including 13 brain regions. Baseline, not perturbation.",rev:"~$175M+ (NIH)",emp:"n/a",hq:"consortium",li:"",pp:"public"},
  {id:"ukbb",n:"UK Biobank",t:4,c:"Population cohort",d:"Genotyping, brain MRI, and health records for ~500k people. Observational.",rev:"~£200M+",emp:"~200-300",hq:"Stockport, UK",li:"https://www.linkedin.com/company/uk-biobank/",pp:"public"},
  {id:"tahoe",n:"Tahoe-100M (Vevo)",t:4,c:"Perturbation dataset",d:"The largest open single-cell drug-perturbation atlas (~100M cells, 1,100 drugs), but on 50 cancer cell lines, not CNS.",rev:"~$20M+ raised (est.)",emp:"~20-40 (est.)",hq:"San Francisco, CA",li:"https://www.linkedin.com/company/tahoe-therapeutics/",pp:"private"},
  {id:"jump",n:"JUMP Cell Painting",t:4,c:"Perturbation dataset",d:"136k+ chemical and genetic perturbations imaged via Cell Painting, on U2OS/A549, not brain.",rev:"consortium",emp:"n/a",hq:"Cambridge, MA",li:"",pp:"public"},
  {id:"lincs",n:"LINCS / CMap",t:4,c:"Perturbation dataset",d:"L1000 transcriptional signatures of drugs and knockdowns, overwhelmingly cancer lines, 978 landmark genes.",rev:"~$100M+ (NIH)",emp:"n/a",hq:"Cambridge, MA",li:"",pp:"public"},
  {id:"recursion",n:"Recursion (RxRx)",t:4,c:"Phenomics + AI",d:"Industrial phenomics image library and Phenom models, on HUVEC and standard lines, not CNS.",rev:"~$82.6M (FY24)",emp:"~600",hq:"Salt Lake City, UT",li:"https://www.linkedin.com/company/recursion-pharmaceuticals/",pp:"public"},
  {id:"arc",n:"Arc Institute",t:4,c:"Virtual cell / models",d:"Genomic foundation models (Evo 2) and the open Virtual Cell Atlas (300M+ cells, hosts Tahoe). None of it CNS perturbation.",rev:"~$650M founding",emp:"few hundred",hq:"Palo Alto, CA",li:"https://www.linkedin.com/company/arc-institute/",pp:"nonprofit"},
  {id:"czi",n:"CZI Virtual Cell",t:4,c:"Virtual cell / models",d:"CELLxGENE platform, GPU compute, and single-cell foundation models. Reference data, no CNS perturbation set.",rev:"CZI (billions to sci)",emp:"n/a",hq:"Redwood City, CA",li:"https://www.linkedin.com/company/chan-zuckerberg-initiative/",pp:"philanthropic"},
  {id:"insitro",n:"Insitro",t:4,c:"AI drug discovery",d:"ML drug discovery generating large in-house iPSC/genomics data, with ALS/neuro programs. Proprietary, not released.",rev:"~$69M ARR",emp:"~260-320",hq:"S. San Francisco, CA",li:"https://www.linkedin.com/company/insitro/",pp:"private"},
  {id:"noetik",n:"Noetik",t:4,c:"Virtual cell / models",d:"Spatial-omics foundation models from in-house multimodal data, on tumors, not brain.",rev:"~$54M raised",emp:"~30-50 (est.)",hq:"S. San Francisco, CA",li:"https://www.linkedin.com/company/noetik/",pp:"private"},
  {id:"vevo",n:"Vevo Therapeutics",t:4,c:"Perturbation platform",d:"The Mosaic platform that generated Tahoe-100M in ~5 weeks. Proven on cancer, no CNS data.",rev:"~$20M+ (est.)",emp:"~20-40 (est.)",hq:"San Francisco, CA",li:"https://www.linkedin.com/company/tahoe-therapeutics/",pp:"private"},
  {id:"genentech_ai",n:"Genentech gRED (lab-in-loop)",t:4,c:"Pharma AI / data",d:"Lab-in-the-loop AI plus large internal Cell Painting and omics data. Neuroscience programs, nothing released.",rev:"Roche pharma ~$50B+",emp:"Genentech ~13,000",hq:"S. San Francisco, CA",li:"https://www.linkedin.com/company/genentech/",pp:"private"},

  // ----- TIER 5: BIOTECH & PHARMA PROGRAMS (group = disease via c) -----
  {id:"lilly",n:"Eli Lilly",t:5,c:"AD",d:"Donanemab and a large AD/neuro discovery engine.",rev:"~$45B",emp:"~47,000",hq:"Indianapolis, IN",li:"",pp:"public"},
  {id:"biogen",n:"Biogen",t:5,c:"AD",d:"Lecanemab partner; biomarker-led AD and ALS discovery.",rev:"~$9.7B",emp:"~8,000",hq:"Cambridge, MA",li:"",pp:"public"},
  {id:"eisai",n:"Eisai",t:5,c:"AD",d:"Lecanemab; genetics-guided dementia discovery at the G2D2 center.",rev:"~$5.5B",emp:"~11,000",hq:"Tokyo, JP",li:"",pp:"public"},
  {id:"roche",n:"Roche / Genentech",t:5,c:"AD",d:"Large neuro discovery plus a deep computational-biology group.",rev:"~$50B+ pharma",emp:"~100,000+",hq:"Basel / S. SF",li:"",pp:"public"},
  {id:"abbvie",n:"AbbVie",t:5,c:"AD",d:"Neurodegeneration and psychiatry discovery, Cambridge-based.",rev:"~$56B",emp:"~50,000",hq:"N. Chicago, IL",li:"",pp:"public"},
  {id:"denali",n:"Denali",t:5,c:"AD",d:"Blood-brain-barrier transport platform; neurodegeneration target discovery.",rev:"clinical-stage",emp:"~500",hq:"S. San Francisco, CA",li:"",pp:"public"},
  {id:"alector",n:"Alector",t:5,c:"ALS/FTD",d:"Immuno-neurology antibodies for AD, FTD, and ALS.",rev:"clinical-stage",emp:"~300",hq:"S. San Francisco, CA",li:"",pp:"public"},
  {id:"voyager",n:"Voyager",t:5,c:"AD",d:"AAV gene therapy with an anti-tau AD program.",rev:"clinical-stage",emp:"~250",hq:"Lexington, MA",li:"",pp:"public"},
  {id:"acumen",n:"Acumen",t:5,c:"AD",d:"Amyloid-beta-oligomer antibody AD program.",rev:"clinical-stage",emp:"~50",hq:"Newton, MA",li:"",pp:"public"},
  {id:"cognition",n:"Cognition Tx",t:5,c:"AD",d:"Sigma-2 program (CT1812) for Alzheimer's and dementia with Lewy bodies.",rev:"clinical-stage",emp:"~50",hq:"Purchase, NY",li:"",pp:"public"},
  {id:"aspen",n:"Aspen Neuroscience",t:5,c:"PD",d:"Autologous iPSC dopaminergic neurons for Parkinson's.",rev:"private",emp:"~100",hq:"San Diego, CA",li:"",pp:"private"},
  {id:"bluerock",n:"BlueRock / Bayer",t:5,c:"PD",d:"iPSC dopaminergic cell therapy for Parkinson's.",rev:"Bayer subsidiary",emp:"~200",hq:"Cambridge, MA",li:"",pp:"private"},
  {id:"quralis",n:"QurAlis",t:5,c:"ALS/FTD",d:"ALS/FTD precision medicine out of the Eggan lab.",rev:"clinical-stage",emp:"~80",hq:"Cambridge, MA",li:"",pp:"private"},
  {id:"aviado",n:"AviadoBio",t:5,c:"ALS/FTD",d:"FTD and ALS gene therapy.",rev:"clinical-stage",emp:"~80",hq:"London, UK",li:"",pp:"private"},
  {id:"praxis",n:"Praxis",t:5,c:"Epilepsy",d:"Ion-channel epilepsies including Dravet-adjacent programs.",rev:"clinical-stage",emp:"~150",hq:"Boston, MA",li:"",pp:"public"},
  {id:"ucb",n:"UCB",t:5,c:"Epilepsy",d:"Epilepsy-anchored pharma; deep ephys/MEA relevance.",rev:"~$6B",emp:"~9,000",hq:"Brussels, BE",li:"",pp:"public"},
  {id:"capsida",n:"Capsida",t:5,c:"Epilepsy",d:"Engineered-AAV gene therapy including STXBP1 epilepsy.",rev:"private",emp:"~200",hq:"Thousand Oaks, CA",li:"",pp:"private"},
  {id:"neurolentech",n:"NEUROLENTECH",t:5,c:"Epilepsy",d:"Patient-derived iPSC models of genetic epilepsies (Dravet anchor).",rev:"private",emp:"~20",hq:"Vienna, AT",li:"",pp:"private"},
  {id:"neurona",n:"Neurona",t:5,c:"Epilepsy",d:"Interneuron cell therapy for drug-resistant focal epilepsy.",rev:"clinical-stage",emp:"~150",hq:"S. San Francisco, CA",li:"",pp:"private"},
  {id:"neumora",n:"Neumora",t:5,c:"Psychiatry",d:"Precision neuropsychiatry discovery across rare and common CNS.",rev:"clinical-stage",emp:"~200",hq:"Watertown, MA",li:"",pp:"public"},
  {id:"alto",n:"Alto Neuroscience",t:5,c:"Psychiatry",d:"EEG/biomarker-driven precision psychiatry.",rev:"clinical-stage",emp:"~80",hq:"Mountain View, CA",li:"",pp:"public"},
  {id:"bms",n:"Bristol Myers Squibb",t:5,c:"Psychiatry",d:"CNS discovery (post-Karuna) with spatial computational biology.",rev:"~$48B",emp:"~34,000",hq:"New York, NY",li:"",pp:"public"},
  {id:"lundbeck",n:"Lundbeck",t:5,c:"Psychiatry",d:"Pure-play CNS pharma with an AI/data-driven discovery push.",rev:"~$3B",emp:"~5,600",hq:"Copenhagen, DK",li:"",pp:"public"},
  {id:"ahead_p",n:"a:head bio",t:5,c:"Platform",d:"Organoid-native CNS drug-discovery biotech.",rev:"pre-revenue",emp:"~18",hq:"Vienna, AT",li:"https://www.linkedin.com/company/aheadbio",pp:"private"},
  {id:"cerevance",n:"Cerevance",t:5,c:"Platform",d:"Human-brain-tissue target discovery (NETSseq) across AD, PD, and more.",rev:"clinical-stage",emp:"~100",hq:"Cambridge, MA",li:"https://www.linkedin.com/company/cerevance",pp:"private"},

  // ----- COVERAGE ADDITIONS (missing sub-functions + verified chokepoints) -----
  {id:"yokogawa",n:"Yokogawa (CellVoyager)",t:0,c:"High-content imaging",d:"CV8000 spinning-disk confocal high-content screening, the workhorse for 3D organoid phenotypic imaging with onboard live-cell incubation.",rev:"part of ~$3.7B parent",emp:"~17,000 (parent)",hq:"Tokyo, JP",li:"https://www.linkedin.com/company/yokogawa-life-science/",pp:"public"},
  {id:"sophion",n:"Sophion Bioscience",t:0,c:"Automated patch-clamp",d:"QPatch/Qube 384 automated patch-clamp for high-throughput ion-channel recording and Dravet-relevant SCN1A pharmacology.",rev:"~$5-15M (est.)",emp:"~95",hq:"Ballerup, DK",li:"https://www.linkedin.com/company/sophion-bioscience/",pp:"private"},
  {id:"s2genomics",n:"S2 Genomics",t:0,c:"Tissue dissociation",d:"The Singulator platform for automated, standardized dissociation of organoids into single cells or nuclei feeding scRNA-seq.",rev:"private, small",emp:"~30-50",hq:"Livermore, CA",li:"https://www.linkedin.com/company/s2-genomics/",pp:"private"},
  {id:"maxcyte",n:"MaxCyte",t:0,c:"Electroporation",d:"ExPERT flow-electroporation for high-viability CRISPR-RNP and mRNA delivery into iPSCs to build isogenic lines.",rev:"~$33M (FY24)",emp:"~91",hq:"Rockville, MD",li:"https://www.linkedin.com/company/maxcyte-inc-/",pp:"public"},
  {id:"orch",n:"Lab orchestration (Automata, Biosero)",t:0,c:"Autonomous-lab software",d:"Schedulers and robotic workcells (Automata LINQ, Biosero Green Button Go, HighRes Cellario) that drive instruments unattended and turn discrete hardware into a closed-loop line.",rev:"mixed",emp:"n/a",hq:"various",li:"",pp:"mixed"},
  {id:"lims",n:"LIMS / ELN (Benchling, eLabFTW)",t:0,c:"Lab data infrastructure",d:"Sample tracking, electronic lab notebook, and metadata/provenance that runs the wet lab and makes the dataset auditable and licensable.",rev:"mixed",emp:"n/a",hq:"various",li:"",pp:"mixed"},
  {id:"insphero",n:"InSphero",t:0,c:"3D culture labware",d:"Akura scaffold-free microtissue plates and Gri3D microwells for standardized, automation-grade organoid culture.",rev:"private",emp:"~50-100",hq:"Schlieren, CH",li:"https://www.linkedin.com/company/insphero-ag",pp:"private"},
  {id:"biolamina",n:"BioLamina",t:1,c:"Defined ECM (laminin)",d:"Full-length recombinant human laminins (Biolaminin 521), the defined, animal-free coating for feeder-free iPSC culture.",rev:"~low tens of M (est.)",emp:"~50-120",hq:"Sundbyberg, SE",li:"https://www.linkedin.com/company/biolamina-ab",pp:"private"},
  {id:"accutase",n:"Accutase (ICT)",t:1,c:"Dissociation enzyme",d:"Accutase gentle cell-detachment solution used to single-cell-passage iPSCs and dissociate organoids for single-cell assays.",rev:"private, small",emp:"<50",hq:"San Diego, CA",li:"https://www.linkedin.com/company/innovative-cell-technologies",pp:"private"},
  {id:"biolife",n:"BioLife (CryoStor)",t:1,c:"Cryopreservation media",d:"CryoStor serum-free freeze media used to bank iPSC lines and organoid intermediates.",rev:"~$80-100M",emp:"~400-500",hq:"Bothell, WA",li:"https://www.linkedin.com/company/biolife-solutions",pp:"public"},
  {id:"vectorbuilder",n:"VectorBuilder",t:1,c:"Viral vector production",d:"Custom AAV, lentivirus, and plasmid design and production used to deliver reporters, CRISPRi/a, and gene-therapy constructs.",rev:"private",emp:"~500+",hq:"Chicago, IL",li:"https://www.linkedin.com/company/vectorbuilder",pp:"private"},
  {id:"quiver",n:"Quiver Bioscience",t:2,c:"Optical electrophysiology",d:"Optopatch all-optical electrophysiology (voltage indicators plus optogenetics) on patient iPSC-neurons for high-throughput functional CNS screening.",rev:"private",emp:"~50-100",hq:"Cambridge, MA",li:"https://www.linkedin.com/company/quiver-bioscience",pp:"private"},
  {id:"bioinfo",n:"Single-cell analysis software",t:4,c:"Bioinformatics software",d:"Cell Ranger, Space Ranger, and the scverse stack (Scanpy, scvi-tools, Squidpy) that turn raw reads into the cell-by-gene matrices the dataset actually is.",rev:"mixed (10x + OSS)",emp:"n/a",hq:"various",li:"",pp:"mixed"},
  {id:"ephys_sw",n:"Ephys analysis software",t:4,c:"Functional-data software",d:"Spike-sorting and network-metric pipelines (Kilosort, SpikeInterface, MEA-NAP) that turn raw MEA traces into the functional-readout modality.",rev:"mostly OSS",emp:"n/a",hq:"various",li:"",pp:"open source"},
  {id:"stoke",n:"Stoke Therapeutics",t:5,c:"Epilepsy",d:"Antisense (TANGO) upregulation of SCN1A for Dravet syndrome.",rev:"clinical-stage",emp:"~200",hq:"Bedford, MA",li:"",pp:"public"},
  {id:"encoded",n:"Encoded Therapeutics",t:5,c:"Epilepsy",d:"Gene therapy (regulated SCN1A) for Dravet syndrome.",rev:"private",emp:"~150",hq:"S. San Francisco, CA",li:"",pp:"private"},

  // ----- SMALL / NICHE PLAYERS (long-tail sweep) -----
  {id:"more",n:"mo:re",t:0,c:"Organoid culture automation",d:"The MO:BOT, a benchtop platform that autonomously generates, feeds, and assays 96-well brain organoids with audit-trail data.",rev:"~€2.3M seed",emp:"~15-25",hq:"Hamburg, DE",li:"https://www.linkedin.com/company/more-science",pp:"private"},
  {id:"monomer",n:"Monomer Bio",t:0,c:"Organoid workcell integrator",d:"AI-driven robotic workcells that automate iPSC-organoid culture from off-the-shelf hardware.",rev:"~$5.6M seed",emp:"~10-20",hq:"San Francisco, CA",li:"https://www.linkedin.com/company/monomerbio",pp:"private"},
  {id:"cellenion",n:"Cellenion (BICO)",t:0,c:"Single-organoid / cell dispensing",d:"spheroONE plates single organoids one per well; cellenONE dispenses single cells for low-input scRNA prep.",rev:"BICO segment",emp:"~20-40",hq:"Lyon, FR",li:"https://www.linkedin.com/company/cellenion",pp:"public"},
  {id:"netri",n:"NETRI",t:0,c:"Neuro organ-on-chip",d:"NeuroFluidics microfluidic chips for iPSC neurons, with an MEA-integrated line for functional CNS readouts.",rev:"~$15M raised",emp:"~30-60",hq:"Lyon, FR",li:"https://www.linkedin.com/company/netri",pp:"private"},
  {id:"camneuro",n:"Cambridge NeuroTech",t:0,c:"Neural ephys probes",d:"High-density silicon probes (128+ channels) for recording electrophysiology inside neural organoids.",rev:"<$10M (est.)",emp:"~10-30",hq:"Cambridge, UK",li:"https://www.linkedin.com/company/cambridge-neurotech-ltd",pp:"private"},
  {id:"honeycomb",n:"Honeycomb Bio (HIVE)",t:0,c:"Single-cell capture",d:"The HIVE picowell device captures and preserves fragile neurons for scRNA-seq, where droplet flows kill them.",rev:"small (est.)",emp:"~30-60",hq:"Waltham, MA",li:"https://www.linkedin.com/company/honeycomb-biotechnologies",pp:"private"},
  {id:"resolve",n:"Resolve Biosciences",t:0,c:"Spatial transcriptomics",d:"Molecular Cartography, a high-sensitivity single-molecule spatial imager for tissue and organoid sections.",rev:"small (est.)",emp:"~30-80",hq:"Monheim, DE",li:"https://www.linkedin.com/company/resolve-biosciences",pp:"private"},
  {id:"curio",n:"Curio Bioscience",t:0,c:"Spatial transcriptomics",d:"Curio Seeker, a sequencing-based whole-transcriptome spatial kit (Slide-seq lineage) at near-single-cell resolution.",rev:"small/early",emp:"~20-50",hq:"Palo Alto, CA",li:"https://www.linkedin.com/company/curio-bioscience",pp:"private"},
  {id:"dolomite",n:"Dolomite Bio",t:0,c:"Single-cell library prep",d:"The Nadia droplet-microfluidic instrument for flexible, open high-throughput scRNA-seq encapsulation.",rev:"Blacktrace segment",emp:"~20-40",hq:"Cambridge, UK",li:"https://www.linkedin.com/company/dolomite-bio",pp:"private"},
  {id:"defbio",n:"Defined Bioscience",t:1,c:"Defined iPSC media",d:"Serum-free fully defined iPSC media (HiDef-B8) and thermostable FGF2 for feeder-free culture.",rev:"<$5M",emp:"~10",hq:"San Diego, CA",li:"https://www.linkedin.com/company/defined-bioscience",pp:"private"},
  {id:"qkine",n:"Qkine",t:1,c:"Animal-free growth factors",d:"100% animal-free recombinant growth factors (FGF2, activin, BMPs, Wnt) for reproducible neural patterning.",rev:"~$3.8M",emp:"~38",hq:"Cambridge, UK",li:"https://www.linkedin.com/company/qkine",pp:"private"},
  {id:"cellguid",n:"Cell Guidance Systems",t:1,c:"Sustained-release growth factors",d:"PODS microcrystals that release growth factors over days to months, suited to long organoid maturation.",rev:"<$5M",emp:"~14-17",hq:"Cambridge, UK",li:"https://www.linkedin.com/company/cell-guidance-systems",pp:"private"},
  {id:"mancbiogel",n:"Manchester BIOGEL",t:1,c:"Synthetic matrix",d:"Synthetic self-assembling peptide hydrogels (PeptiGels) as defined, animal-free 3D matrices for organoids.",rev:"<$5M",emp:"~8-12",hq:"Alderley Park, UK",li:"https://www.linkedin.com/company/mancbiogel",pp:"private"},
  {id:"elixirgen",n:"Elixirgen Scientific",t:1,c:"Rapid differentiation kits",d:"Quick-Neuron kits and ready-made iPSC neurons that differentiate in 1-2 weeks, plus AD disease panels.",rev:"~$9M",emp:"~20",hq:"Baltimore, MD",li:"https://www.linkedin.com/company/elixirgen-scientific",pp:"private"},
  {id:"reprocell",n:"REPROCELL / StemFit",t:1,c:"iPSC media (regional)",d:"StemFit defined animal-free iPSC media (Ajinomoto-made, incl. GMP), plus reprogramming and AD-neuron supply.",rev:"~$30-50M",emp:"~150-250",hq:"Yokohama, JP",li:"https://www.linkedin.com/company/reprocell",pp:"public"},
  {id:"neuracell",n:"NeuraCell",t:2,c:"Brain organoid / line supply",d:"Ready-to-order forebrain/midbrain iPSC organoids at defined maturity plus tauopathy (MAPT) lines for AD work.",rev:"<$5M",emp:"~10-30",hq:"Albany, NY",li:"https://www.linkedin.com/company/neuracell",pp:"nonprofit"},
  {id:"cortical",n:"Cortical Labs",t:2,c:"Neuron-on-MEA biocomputing",d:"The CL1 system wiring ~800k iPSC neurons onto a MEA chip with closed-loop stimulation, the closest analog to a neuron-on-chip loop.",rev:"<$5M",emp:"~35",hq:"Melbourne, AU",li:"https://www.linkedin.com/company/cortical-labs",pp:"private"},
  {id:"finalspark",n:"FinalSpark",t:2,c:"Organoid biocomputing",d:"Remote-access living brain organoids on electrode arrays, streaming longitudinal MEA stimulus-response data.",rev:"<$2M",emp:"~6-20",hq:"Vevey, CH",li:"https://www.linkedin.com/company/finalspark",pp:"private"},
  {id:"tempo",n:"Tempo Bioscience",t:2,c:"Specialist iPSC neurons",d:"Non-viral serum-free iPSC neuron and glia subtypes (iSenso sensory neurons, 25+ subtypes) for disease modeling.",rev:"<$5M",emp:"~5-20",hq:"S. San Francisco, CA",li:"https://www.linkedin.com/company/tempo-bioscience-inc",pp:"private"},
  {id:"ixcells",n:"iXCells Biotech",t:3,c:"Preclinical iPSC CRO",d:"iPSC lines, iPSC-derived neurons, custom iPSC generation, 3D models, and compound-screening assays.",rev:"~$4-7M",emp:"~44",hq:"San Diego, CA",li:"https://www.linkedin.com/company/ixcells-biotechnologies",pp:"private"},

  // ----- GAP NODES (verified absences, not suppliers) -----
  {id:"g_cnsdata",n:"CNS perturbation data",t:4.05,c:"GAP",d:"",k:"gap",w:"Cancer has Tahoe-100M (100M cells, 1,100 drugs, fifty times all prior public perturbation data). No human brain or brain-organoid equivalent exists. The CNS perturbation work that does exist is small genetic or developmental screens (tens of thousands of cells), not a therapeutic drug atlas at scale."},
  {id:"g_multi",n:"Linked multimodal data",t:4.35,c:"GAP",d:"",k:"gap",w:"No standardized data product co-registers single-cell, spatial, electrophysiology, and imaging on the same individual organoid. The closest work hits two or three modalities in one-off studies, or links four on brain slices, never four on one organoid. The linkage layer is missing."},
  {id:"g_cnsvc",n:"Predictive CNS virtual cell",t:4.2,c:"GAP",d:"",k:"gap",w:"The race to build virtual cells (Arc, CZI, Insitro) runs on perturbation data, and for neurons that data barely exists, so no model predicts how a human neuron answers a drug. Neurons are well covered in observational atlases; the binding absence is perturbation-response data, not raw neurons or compute."},
  {id:"g_predict",n:"Predictive human CNS model",t:2.75,c:"GAP",d:"",k:"gap",w:"Only about 6 to 8% of CNS candidates that reach Phase I make it to market, most failing on human efficacy. No human in-vitro system is yet validated to predict clinical CNS response. The cardiac field has a validated trial-in-a-dish; CNS has no equivalent."},
  {id:"g_mature",n:"Aged / adult organoid maturation",t:2.45,c:"GAP",d:"",k:"gap",w:"Brain organoids plateau at fetal-to-early-postnatal stages even after years in culture; five-year organoids still only reach early childhood. Shortcut tricks (progerin, aged-donor conversion, transplantation) can force aged-like phenotypes, but nothing genuinely ages them to the decades-old brain Alzheimer's needs."},
  {id:"g_auto",n:"Reproducible automated production",t:1.6,c:"GAP",d:"",k:"gap",w:"The pieces exist separately: semi-automated uniform organoids, an automated midbrain workflow, prototype closed-loop maintenance rigs, reproducible thousands made by hand. No platform integrates them into closed-loop, reproducible production of cortical organoids across the full 100+ day course at dataset scale."},
  {id:"g_matrix",n:"Defined synthetic matrix",t:1.05,c:"GAP",d:"",k:"gap",w:"The flip side of the Matrigel chokepoint: there is no defined, xeno-free synthetic hydrogel that matches mouse-tumor extract for brain-organoid budding at production scale. VitroGel, PEG gels, and Cellendes exist but none is a validated drop-in, so batch variability and clean data provenance stay unsolved."},
  {id:"g_vasc",n:"Vascularization / perfusion",t:2.15,c:"GAP",d:"",k:"gap",w:"Organoids have no blood supply, so diffusion limits create necrotic cores that cap viable size at a few millimeters and bias which cells you can even read. No scalable way to perfuse or vascularize them exists, which limits how large, how old, and how representative any dataset's cells can be."},
  {id:"g_allelic",n:"Isogenic CNS allelic series",t:2.6,c:"GAP",d:"",k:"gap",w:"For genetics-anchored CNS work (APOE/APP/PSEN in AD, SCN1A in Dravet) there is no off-the-shelf, deeply characterized isogenic variant library in a common background at the scale a perturbation atlas needs. KOLF2.1J fixes the background; the edited panels are still re-derived bespoke per lab."},
  {id:"g_qc",n:"Organoid QC ground-truth",t:4.5,c:"GAP",d:"",k:"gap",w:"There is no accepted reference standard for what a correct organoid is, no quantitative spec for regional identity, cell composition, or off-target fates that defines a pass. HNOCA describes organoids, it does not grade them. Without a ground-truth, baseline drift confounds any perturbation signal."},
];

// LINKS — real dependencies: who actually supplies, feeds, or depends on whom.
// r = a short relationship shown on the edge when you hover (how s connects to t).
const LINKS = [
  // ---- ECM / matrix: the Matrigel class feeds every organoid maker; defined matrices chase the gap ----
  {s:"corning",t:"ahead_m",r:"the Matrigel its organoids grow in"},
  {s:"corning",t:"bot",r:"the Matrigel its organoids grow in"},
  {s:"corning",t:"organoth",r:"the Matrigel its assembloids grow in"},
  {s:"corning",t:"neuracell",r:"the Matrigel its organoids grow in"},
  {s:"corning",t:"insphero",r:"the matrix used in its 3D plates"},
  {s:"corning",t:"bitbio",r:"ECM coating for the iPSC culture"},
  {s:"corning",t:"g_matrix",r:"the defined replacement it lacks"},
  {s:"corning",t:"g_auto",r:"the lot-variable ECM that drives batch noise"},
  {s:"amsbio",t:"corning",r:"the #2 BME, same mouse-tumor source"},
  {s:"amsbio",t:"g_matrix",r:"animal-derived, not the defined fix"},
  {s:"cellendes",t:"g_matrix",r:"defined PEG gel chasing the replacement"},
  {s:"mancbiogel",t:"g_matrix",r:"synthetic peptide gel chasing the replacement"},
  {s:"mancbiogel",t:"ahead_m",r:"defined matrix option for organoids"},
  {s:"biolamina",t:"bitbio",r:"the defined laminin coating under the cells"},
  {s:"biolamina",t:"cdi_m",r:"defined coating for manufacturing"},
  {s:"biolamina",t:"g_matrix",r:"a defined coating, but not full matrix"},
  // ---- media + growth factors -> organoid/neuron makers ----
  {s:"gibco",t:"ahead_m",r:"media and neural supplements"},
  {s:"gibco",t:"bitbio",r:"media for the iPSC lines"},
  {s:"gibco",t:"bot",r:"media and supplements"},
  {s:"gibco",t:"neuracell",r:"media for the organoids"},
  {s:"stemcell",t:"ahead_m",r:"the cerebral-organoid differentiation kits"},
  {s:"stemcell",t:"bot",r:"organoid differentiation reagents"},
  {s:"stemcell",t:"organoth",r:"differentiation reagents"},
  {s:"stemcell",t:"bitbio",r:"mTeSR iPSC maintenance media"},
  {s:"defbio",t:"bitbio",r:"lower-cost defined iPSC media"},
  {s:"defbio",t:"stemcell",r:"the cheaper defined-media challenger"},
  {s:"reprocell",t:"bitbio",r:"StemFit defined iPSC media (regional)"},
  {s:"reprocell",t:"stemcell",r:"the Japan-anchored media alternative"},
  {s:"peprotech",t:"ahead_m",r:"growth factors for patterning"},
  {s:"peprotech",t:"brainxell",r:"growth factors for differentiation"},
  {s:"biotechne",t:"ahead_m",r:"growth factors and small molecules"},
  {s:"biotechne",t:"bitbio",r:"small molecules for induction"},
  {s:"qkine",t:"ahead_m",r:"animal-free growth factors"},
  {s:"qkine",t:"peprotech",r:"the animal-free GF challenger"},
  {s:"cellguid",t:"ahead_m",r:"slow-release factors for long maturation"},
  {s:"cellguid",t:"g_mature",r:"sustained factors aimed at maturation"},
  {s:"merck_ls",t:"ahead_m",r:"broad reagent backbone"},
  {s:"cst",t:"ahead_m",r:"validation antibodies"},
  {s:"cst",t:"g_multi",r:"antibodies for the imaging modality"},
  {s:"biolegend",t:"g_multi",r:"antibodies for CITE-seq multimodal"},
  // ---- reference & patient lines -> cell/model makers ----
  {s:"jax",t:"bitbio",r:"KOLF2.1J reference line they build on"},
  {s:"jax",t:"brainxell",r:"reference line for differentiation"},
  {s:"jax",t:"cdi_m",r:"reference line basis"},
  {s:"jax",t:"ahead_m",r:"reference line for the organoids"},
  {s:"jax",t:"g_allelic",r:"fixes the background, not the variants"},
  {s:"jax",t:"g_predict",r:"the reference genome models benchmark on"},
  {s:"wicell",t:"jax",r:"banks the KOLF2 parental line"},
  {s:"wicell",t:"bitbio",r:"reference pluripotent lines"},
  {s:"coriell",t:"g_allelic",r:"patient cells for disease variants"},
  {s:"coriell",t:"neuracell",r:"patient-derived lines"},
  {s:"coriell",t:"g_predict",r:"patient cells a real model needs"},
  {s:"cdi_r",t:"cdi_m",r:"the iPSC source it manufactures from"},
  // ---- editing: reagents + electroporation + viral -> edited lines, variant gap ----
  {s:"idt",t:"synthego",r:"CRISPR oligos behind the edits"},
  {s:"twist",t:"synthego",r:"synthetic DNA for the guides"},
  {s:"addgene",t:"synthego",r:"the published constructs the edits use"},
  {s:"addgene",t:"bitbio",r:"the CRISPR constructs the lines use"},
  {s:"addgene",t:"g_allelic",r:"the plasmids behind variant lines"},
  {s:"synthego",t:"bitbio",r:"guide RNAs and edited lines"},
  {s:"synthego",t:"g_allelic",r:"edited lines for the variant series"},
  {s:"lonza",t:"bitbio",r:"the Nucleofector that delivers the edits"},
  {s:"lonza",t:"g_allelic",r:"electroporates the variant edits"},
  {s:"maxcyte",t:"bitbio",r:"flow-electroporation of the edits"},
  {s:"maxcyte",t:"lonza",r:"the competing electroporation platform"},
  {s:"maxcyte",t:"g_allelic",r:"builds the variant lines at scale"},
  {s:"vectorbuilder",t:"bitbio",r:"viral delivery of constructs"},
  {s:"vectorbuilder",t:"capsida",r:"AAV tooling for gene therapy"},
  {s:"vectorbuilder",t:"voyager",r:"AAV tooling for gene therapy"},
  {s:"vectorbuilder",t:"aviado",r:"viral vectors for gene therapy"},
  // ---- dissociation + cryo -> single-cell prep, banking ----
  {s:"accutase",t:"ahead_m",r:"dissociates organoids to single cells"},
  {s:"accutase",t:"s2genomics",r:"the dissociation enzyme it runs"},
  {s:"accutase",t:"bitbio",r:"gentle passaging of the iPSCs"},
  {s:"s2genomics",t:"tenx",r:"dissociates organoids before single-cell"},
  {s:"s2genomics",t:"honeycomb",r:"single-cell prep before capture"},
  {s:"miltenyi",t:"tenx",r:"dissociation kits for single-cell prep"},
  {s:"miltenyi",t:"ahead_m",r:"dissociation of the organoids"},
  {s:"cellenion",t:"tenx",r:"single-cell dispensing into scRNA prep"},
  {s:"cellenion",t:"ahead_m",r:"sorts single organoids one per well"},
  {s:"biolife",t:"bitbio",r:"CryoStor freeze media to bank the lines"},
  {s:"biolife",t:"ahead_m",r:"banking organoid intermediates"},
  {s:"biolife",t:"jax",r:"freeze media to bank the reference line"},
  // ---- single-cell + spatial instruments -> data/atlas/modalities, sequencing ----
  {s:"tenx",t:"hnoca",r:"Chromium single-cell behind the atlas"},
  {s:"tenx",t:"ahead_m",r:"single-cell profiling of the organoids"},
  {s:"tenx",t:"bioinfo",r:"raw reads the software processes"},
  {s:"tenx",t:"illumina",r:"libraries sequenced on Illumina"},
  {s:"tenx",t:"g_multi",r:"the transcriptomic and spatial modality"},
  {s:"tenx",t:"g_cnsdata",r:"the read-out the dataset needs"},
  {s:"parse",t:"tenx",r:"the instrument-free scRNA alternative"},
  {s:"parse",t:"hnoca",r:"split-pool scRNA into the atlas"},
  {s:"parse",t:"illumina",r:"libraries sequenced on Illumina"},
  {s:"scalebio",t:"tenx",r:"high-throughput scRNA alternative"},
  {s:"dolomite",t:"tenx",r:"open droplet scRNA alternative"},
  {s:"dolomite",t:"illumina",r:"libraries sequenced on Illumina"},
  {s:"honeycomb",t:"tenx",r:"neuron-friendly capture vs droplets"},
  {s:"honeycomb",t:"illumina",r:"preserved cells sequenced on Illumina"},
  {s:"bruker_sp",t:"g_multi",r:"a spatial modality (imager, no sequencer)"},
  {s:"bruker_sp",t:"tenx",r:"the CosMx spatial competitor to Xenium"},
  {s:"vizgen",t:"g_multi",r:"a MERFISH spatial modality"},
  {s:"resolve",t:"g_multi",r:"a single-molecule spatial modality"},
  {s:"resolve",t:"tenx",r:"imaging-spatial alternative to Xenium"},
  {s:"curio",t:"g_multi",r:"sequencing-based whole-transcriptome spatial"},
  {s:"curio",t:"illumina",r:"spatial libraries sequenced on Illumina"},
  {s:"akoya",t:"g_multi",r:"spatial-proteomics modality"},
  // ---- sequencing -> analysis, atlases, data ----
  {s:"illumina",t:"bioinfo",r:"the reads the software analyzes"},
  {s:"illumina",t:"hnoca",r:"sequences the organoid libraries"},
  {s:"illumina",t:"allen",r:"sequences the atlas reads"},
  {s:"illumina",t:"rosmap",r:"sequences the cohort"},
  {s:"illumina",t:"azenta",r:"the sequencer the service runs"},
  {s:"illumina",t:"g_cnsdata",r:"the read-out under the dataset"},
  {s:"element",t:"illumina",r:"the cheaper sequencer eroding the moat"},
  {s:"pacbio",t:"illumina",r:"long-read complement to short-read"},
  {s:"nanopore",t:"illumina",r:"long-read complement to short-read"},
  // ---- MEA + ephys -> assays, CROs, modality, analysis ----
  {s:"maxwell",t:"ahead_m",r:"HD-MEA recording of organoid activity"},
  {s:"maxwell",t:"ephys_sw",r:"raw traces it spike-sorts"},
  {s:"maxwell",t:"g_multi",r:"the electrophysiology modality"},
  {s:"3brain",t:"maxwell",r:"the rival HD-MEA"},
  {s:"3brain",t:"ephys_sw",r:"traces into the same pipelines"},
  {s:"axion",t:"neucyte",r:"MEA hardware under the assay"},
  {s:"axion",t:"netri",r:"the MEA powering its chips"},
  {s:"axion",t:"ephys_sw",r:"plate-MEA traces it analyzes"},
  {s:"axion",t:"g_multi",r:"plate-based MEA modality"},
  {s:"mcs",t:"ephys_sw",r:"incumbent MEA into analysis"},
  {s:"camneuro",t:"ephys_sw",r:"probe recordings it spike-sorts"},
  {s:"camneuro",t:"maxwell",r:"penetrating-probe alternative to HD-MEA"},
  {s:"nanion",t:"metrion",r:"automated patch-clamp the CRO runs"},
  {s:"sophion",t:"nanion",r:"the other automated patch-clamp vendor"},
  {s:"sophion",t:"praxis",r:"SCN1A pharmacology for epilepsy"},
  {s:"nanion",t:"praxis",r:"ion-channel screening for epilepsy"},
  {s:"quiver",t:"g_predict",r:"optical ephys, still not predictive"},
  {s:"quiver",t:"praxis",r:"functional readout for epilepsy"},
  // ---- imaging -> organoid makers, QC, analysis ----
  {s:"yokogawa",t:"ahead_m",r:"confocal imaging of the organoids"},
  {s:"yokogawa",t:"bioinfo",r:"images the analysis quantifies"},
  {s:"moldev",t:"ahead_m",r:"high-content imaging of organoids"},
  {s:"moldev",t:"g_qc",r:"imaging a QC standard would use"},
  {s:"revvity",t:"ahead_m",r:"high-content imaging for screens"},
  {s:"revvity",t:"honeycomb",r:"co-markets its HIVE capture"},
  {s:"nikon",t:"ahead_m",r:"live imaging of organoids"},
  {s:"zeiss",t:"ahead_m",r:"light-sheet imaging in 3D"},
  {s:"leica",t:"bot",r:"confocal imaging"},
  {s:"cephla",t:"g_auto",r:"low-cost QC imaging for scale"},
  // ---- culture / labware / automation -> organoid makers, the automation gap ----
  {s:"phc",t:"ahead_m",r:"tri-gas incubators for culture"},
  {s:"sartorius_hw",t:"ahead_m",r:"live-cell imaging in the incubator"},
  {s:"sartorius_hw",t:"g_auto",r:"bioreactors for scaled culture"},
  {s:"cytena",t:"g_auto",r:"single-cell printing for clonality"},
  {s:"insphero",t:"ahead_m",r:"the labware organoids grow in"},
  {s:"insphero",t:"g_auto",r:"automation-grade plates for scale"},
  {s:"hamilton",t:"g_auto",r:"liquid handling automation runs on"},
  {s:"tecan",t:"g_auto",r:"liquid handling automation runs on"},
  {s:"opentrons",t:"g_auto",r:"low-cost automation option"},
  {s:"sptlabtech",t:"azenta",r:"nanoliter prep for the service"},
  {s:"beckman",t:"g_auto",r:"liquid handling for the pipeline"},
  {s:"orch",t:"hamilton",r:"schedules the liquid handlers"},
  {s:"orch",t:"g_auto",r:"the control layer automation needs"},
  {s:"orch",t:"lims",r:"feeds run metadata to the record"},
  {s:"more",t:"g_auto",r:"all-in-one organoid automation"},
  {s:"more",t:"ahead_m",r:"benchtop rival to a custom workcell"},
  {s:"monomer",t:"g_auto",r:"workcell integration for organoid culture"},
  {s:"monomer",t:"orch",r:"the integrator vs the scheduler"},
  // ---- LIMS / bioinformatics / ephys software -> the dataset and QC ----
  {s:"lims",t:"g_qc",r:"provenance a QC standard needs"},
  {s:"lims",t:"hnoca",r:"metadata behind a publishable dataset"},
  {s:"bioinfo",t:"hnoca",r:"builds the matrices behind the atlas"},
  {s:"bioinfo",t:"g_cnsdata",r:"turns reads into the dataset"},
  {s:"bioinfo",t:"g_qc",r:"the analysis a QC standard would use"},
  {s:"ephys_sw",t:"g_multi",r:"turns MEA traces into the modality"},
  // ---- organoid makers -> the gaps they all face + the atlas ----
  {s:"ahead_m",t:"g_mature",r:"its organoids stall before adulthood"},
  {s:"ahead_m",t:"g_auto",r:"still produced largely by hand"},
  {s:"ahead_m",t:"g_vasc",r:"its organoids have no blood supply"},
  {s:"ahead_m",t:"g_predict",r:"organoids not yet predictive"},
  {s:"ahead_m",t:"hnoca",r:"organoid data feeding the atlas"},
  {s:"bot",t:"g_mature",r:"organoids stall at fetal stage"},
  {s:"bot",t:"g_predict",r:"screening, not yet predictive"},
  {s:"organoth",t:"g_mature",r:"assembloids stall too"},
  {s:"organoth",t:"g_predict",r:"PD model, not yet predictive"},
  {s:"neuracell",t:"hnoca",r:"tauopathy organoid lines into the atlas"},
  {s:"neuracell",t:"g_mature",r:"organoids still developmentally young"},
  {s:"cortical",t:"ephys_sw",r:"neuron-on-MEA data into spike-sorting"},
  {s:"cortical",t:"g_auto",r:"closed-loop neuron-on-chip analog"},
  {s:"finalspark",t:"ephys_sw",r:"longitudinal MEA data into analysis"},
  // ---- iPSC neuron / chip makers -> the predictive-model gap ----
  {s:"bitbio",t:"g_predict",r:"defined cells, still not predictive"},
  {s:"cdi_m",t:"g_predict",r:"iPSC neurons, still not predictive"},
  {s:"brainxell",t:"g_predict",r:"neuron subtypes, still not predictive"},
  {s:"neucyte",t:"g_predict",r:"functional assay, still not predictive"},
  {s:"axol",t:"g_predict",r:"disease-model cells, not yet predictive"},
  {s:"ncardia",t:"g_predict",r:"iPSC assays, not yet predictive"},
  {s:"anatomic",t:"g_predict",r:"sensory neurons, narrow readout"},
  {s:"tempo",t:"g_predict",r:"specialist neurons, narrow readout"},
  {s:"elixirgen",t:"cdi_m",r:"rapid-differentiation neuron alternative"},
  {s:"elixirgen",t:"g_predict",r:"fast neurons, still not predictive"},
  {s:"emulate_m",t:"g_predict",r:"organ-chip, not yet validated predictive"},
  {s:"mimetas",t:"g_predict",r:"organ-chip, not yet predictive"},
  {s:"cnbio",t:"g_predict",r:"organ-chip, not yet predictive"},
  {s:"hesperos",t:"g_predict",r:"functional chip, not yet predictive"},
  {s:"axosim",t:"g_predict",r:"nerve/organoid chip, not yet predictive"},
  {s:"netri",t:"g_predict",r:"neuro chip, not yet predictive"},
  {s:"emulate_hw",t:"emulate_m",r:"the instrument behind the chip model"},
  // ---- iPSC supply ecosystem / Yamanaka IP ----
  {s:"yamanaka",t:"cdi_m",r:"reprogramming IP it manufactures under"},
  {s:"yamanaka",t:"bitbio",r:"reprogramming freedom-to-operate"},
  {s:"yamanaka",t:"reprocell",r:"the reprogramming IP it licenses"},
  // ---- human tissue -> atlases + predictive gap ----
  {s:"netseq",t:"allen",r:"human-tissue profiling into atlases"},
  {s:"netseq",t:"rosmap",r:"cell-type-specific human brain data"},
  {s:"bioivt",t:"g_predict",r:"human tissue a model needs"},
  {s:"bioivt",t:"rosmap",r:"biospecimens behind cohorts"},
  {s:"neurobiobank",t:"bioivt",r:"the public banks behind most tissue"},
  {s:"neurobiobank",t:"rosmap",r:"the brains behind the cohorts"},
  // ---- atlases / cohorts -> the data gap + QC ----
  {s:"allen",t:"hnoca",r:"reference the organoid atlas maps to"},
  {s:"hca",t:"hnoca",r:"healthy-cell reference"},
  {s:"hnoca",t:"g_cnsdata",r:"an atlas, but no perturbation arms"},
  {s:"hnoca",t:"g_qc",r:"describes organoids, doesn't grade them"},
  {s:"rosmap",t:"g_cnsdata",r:"human brain data, but observational"},
  {s:"gtex",t:"rosmap",r:"tissue reference behind the cohort"},
  {s:"ukbb",t:"rosmap",r:"population data alongside"},
  // ---- perturbation datasets + AI -> the virtual-cell gap ----
  {s:"vevo",t:"tahoe",r:"the platform that made Tahoe-100M"},
  {s:"tahoe",t:"arc",r:"open perturbation data in the atlas"},
  {s:"tahoe",t:"g_cnsvc",r:"perturbation data, but cancer not CNS"},
  {s:"jump",t:"recursion",r:"image-perturbation data"},
  {s:"lincs",t:"g_cnsvc",r:"old signatures, mostly cancer"},
  {s:"noetik",t:"g_cnsvc",r:"tumor models, not CNS"},
  {s:"recursion",t:"g_cnsvc",r:"phenomics, but not CNS"},
  {s:"g_cnsdata",t:"g_cnsvc",r:"the data a virtual neuron would train on"},
  {s:"g_cnsvc",t:"arc",r:"the CNS coverage Arc's models lack"},
  {s:"g_cnsvc",t:"czi",r:"the CNS coverage CZI's models lack"},
  {s:"g_cnsvc",t:"insitro",r:"the CNS data neuro AI lacks"},
  {s:"g_cnsvc",t:"genentech_ai",r:"the CNS perturbation its models lack"},
  {s:"genentech_ai",t:"roche",r:"Roche's own internal AI engine"},
  // ---- gap interlinks (the chain converges here) ----
  {s:"g_qc",t:"g_cnsdata",r:"no QC standard, no comparable data"},
  {s:"g_predict",t:"g_cnsdata",r:"a predictive model is what the data unlocks"},
  {s:"g_mature",t:"g_predict",r:"maturation precondition for prediction"},
  {s:"g_vasc",t:"g_mature",r:"no perfusion caps how old they get"},
  {s:"g_vasc",t:"g_predict",r:"necrotic cores bias what a model sees"},
  {s:"g_auto",t:"g_predict",r:"scale precondition for prediction"},
  {s:"g_matrix",t:"g_auto",r:"a defined matrix is half the reproducibility fix"},
  {s:"g_multi",t:"g_cnsdata",r:"linked modalities part of the missing data"},
  {s:"g_allelic",t:"g_cnsdata",r:"the genetic-perturbation substrate"},
  {s:"g_allelic",t:"g_predict",r:"genetics-anchored models need it"},
  // ---- CROs wire models/instruments to programs ----
  {s:"charles",t:"g_predict",r:"safety CRO, same missing model"},
  {s:"nhp",t:"charles",r:"the primate supply its tox depends on"},
  {s:"nhp",t:"wuxi",r:"the primate supply gating IND tox"},
  {s:"evotec",t:"bitbio",r:"screens on iPSC neurons"},
  {s:"evotec",t:"g_predict",r:"iPSC discovery CRO, same gap"},
  {s:"wuxi",t:"g_predict",r:"outsourced discovery, same gap"},
  {s:"pharmaron",t:"g_predict",r:"outsourced discovery, same gap"},
  {s:"crownbio",t:"mimetas",r:"organoid CRO using chip models"},
  {s:"cellesce",t:"g_auto",r:"organoid bioprocess scale-up"},
  {s:"neuroproof",t:"axion",r:"MEA CRO running Axion hardware"},
  {s:"metrion",t:"sophion",r:"ion-channel CRO using patch-clamp"},
  {s:"azenta",t:"illumina",r:"the sequencer the service runs"},
  {s:"azenta",t:"hnoca",r:"sequencing service behind the data"},
  {s:"c28bio",t:"maxwell",r:"organoid-MEA CRO on HD-MEA"},
  {s:"definigen",t:"bitbio",r:"custom iPSC line generation"},
  {s:"ixcells",t:"bitbio",r:"iPSC lines and custom models"},
  {s:"ixcells",t:"g_predict",r:"iPSC CRO, same missing model"},
  // ---- platform biotech ----
  {s:"ahead_p",t:"ahead_m",r:"runs this organoid platform"},
  {s:"cerevance",t:"netseq",r:"runs the NETSseq platform"},
  // ---- pharma demand pulling down onto the gaps ----
  {s:"lilly",t:"g_cnsdata",r:"its AD programs need this data"},
  {s:"denali",t:"g_cnsdata",r:"its neuro targets need it"},
  {s:"roche",t:"g_cnsdata",r:"its neuro discovery needs it"},
  {s:"biogen",t:"g_cnsdata",r:"its AD and ALS need it"},
  {s:"eisai",t:"g_predict",r:"needs a predictive model"},
  {s:"abbvie",t:"g_predict",r:"needs a predictive model"},
  {s:"acumen",t:"g_predict",r:"its AD program needs it"},
  {s:"cognition",t:"g_predict",r:"needs a predictive model"},
  {s:"alector",t:"g_cnsdata",r:"immuno-neurology needs the data"},
  {s:"voyager",t:"g_predict",r:"gene-therapy targets need it"},
  {s:"praxis",t:"g_multi",r:"epilepsy needs the ephys modality"},
  {s:"ucb",t:"g_multi",r:"epilepsy needs ephys readouts"},
  {s:"neurolentech",t:"g_predict",r:"Dravet models need prediction"},
  {s:"capsida",t:"g_predict",r:"needs a predictive model"},
  {s:"neurona",t:"g_multi",r:"cell therapy needs functional data"},
  {s:"quralis",t:"g_predict",r:"ALS/FTD needs a predictive model"},
  {s:"aviado",t:"g_predict",r:"FTD and ALS need it"},
  {s:"neumora",t:"g_cnsdata",r:"precision psychiatry needs the data"},
  {s:"alto",t:"g_cnsdata",r:"biomarker psychiatry needs it"},
  {s:"bms",t:"g_cnsdata",r:"its CNS pipeline needs it"},
  {s:"lundbeck",t:"g_cnsdata",r:"pure-play CNS needs it most"},
  {s:"aspen",t:"g_mature",r:"PD cell therapy needs mature neurons"},
  {s:"bluerock",t:"g_mature",r:"needs mature dopaminergic neurons"},
  {s:"stoke",t:"g_multi",r:"Dravet needs the ephys readout"},
  {s:"encoded",t:"g_predict",r:"Dravet gene therapy needs a model"},
  // flow cytometry + metabolic flux readouts
  {s:"bd",t:"cdi_m",r:"sorts and QCs the iPSC-derived cells"},
  {s:"bd",t:"ahead_m",r:"sorts cells from dissociated organoids"},
  {s:"cytek",t:"bd",r:"the spectral-flow alternative"},
  {s:"cytek",t:"cdi_m",r:"spectral cytometry QC of the cells"},
  {s:"agilent",t:"ahead_m",r:"Seahorse metabolic-flux readout of the organoids"},
  {s:"agilent",t:"g_multi",r:"a metabolic readout option"},
];

// drop links that reference a non-existent id (typo guard)
const _ids = new Set(NODES.map(n=>n.id));
const CLEAN_LINKS = LINKS.filter(l=>_ids.has(l.s)&&_ids.has(l.t));
